In [125]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.subplots as sp
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings

In [126]:
warnings.simplefilter(action='ignore', category=FutureWarning)
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

In [127]:
wp = pd.read_csv(r"C:\\Users\\AMITESH\\OneDrive\\Desktop\\World_population\\world_population.csv", encoding="latin1")
wp.head()
wp.shape
wp.isnull().sum()
print(f'Amount of Duplicates:{wp.duplicated().sum()}')
wp.columns

Amount of Duplicates:0

Index(['Rank', 'Country/Territory', 'Continent', '2022 Population',
       '2020 Population', '2015 Population', '2010 Population',
       '2000 Population', '1990 Population', '1980 Population',
       '1970 Population', 'Area (kmÃÂÃÂ²)', 'Density (per kmÃÂÃÂ²)',
       'Growth Rate', 'World Population Percentage', 'Area per Person',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35',
       'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39',
       'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47',
       'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51',
       'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55',
       'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59',
       'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63',
       'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67',
       'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70', 'Unnamed: 71',
       'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74', 'Unnamed: 75',
       'Unnamed: 76', 'Unnamed: 77'],
      dtype='str')

In [128]:
wp.sort_values(by = 'Country/Territory',ascending=True)

,Rank,Country/Territory,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,...,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77
0,36,Afghanistan,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,138,Albania,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,34,Algeria,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,213,American Samoa,Oceania,44273,46189,51368,54849,58230,47818,32886,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,203,Andorra,Europe,79824,77700,71746,71519,66097,53569,35611,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,Wallis and Futuna,Oceania,11572,11655,12182,13142,14723,13454,11315,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,172,Western Sahara,Africa,575986,556048,491824,413296,270375,178529,116775,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
231,46,Yemen,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232,63,Zambia,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233,74,Zimbabwe,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [129]:
wp.isnull().sum()

Rank                   0
Country/Territory      0
Continent              0
2022 Population        0
2020 Population        0
                    ...
Unnamed: 73          234
Unnamed: 74          234
Unnamed: 75          234
Unnamed: 76          234
Unnamed: 77          234
Length: 78, dtype: int64

In [130]:
wp.drop(["CCA3","Capital"],axis=1,inplace=True, errors='ignore')

In [131]:
countries_by_continent = wp.groupby('Continent').size().reset_index(name='count')

In [132]:
wp.head()
wp.tail()
custom_palette = ['#0b3d91', '#e0f7fa', '#228b22', '#1e90ff', '#8B4513', '#D2691E',
'#DAA520', '#556B2F']

fig= px.bar(countries_by_continent,
            x='Continent',
            y='count',
            color='Continent',
            text='count',
            title='Number of Countires by Contitnent',
           color_discrete_sequence = custom_palette )

In [133]:
wp["Rank"]

0       36
1      138
2       34
3      213
4      203
      ...
229    226
230    172
231     46
232     63
233     74
Name: Rank, Length: 234, dtype: int64

In [134]:
wp.head().sort_values(by = "Country/Territory",ascending= False)

,Rank,Country/Territory,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,...,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77
4,203,Andorra,Europe,79824,77700,71746,71519,66097,53569,35611,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,213,American Samoa,Oceania,44273,46189,51368,54849,58230,47818,32886,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,34,Algeria,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,138,Albania,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,36,Afghanistan,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [135]:
wp.tail()

,Rank,Country/Territory,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,...,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77
229,226,Wallis and Futuna,Oceania,11572,11655,12182,13142,14723,13454,11315,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,172,Western Sahara,Africa,575986,556048,491824,413296,270375,178529,116775,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
231,46,Yemen,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232,63,Zambia,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233,74,Zimbabwe,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [136]:
wp.tail().sort_values(by='Country/Territory',ascending=True)

,Rank,Country/Territory,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,...,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77
229,226,Wallis and Futuna,Oceania,11572,11655,12182,13142,14723,13454,11315,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,172,Western Sahara,Africa,575986,556048,491824,413296,270375,178529,116775,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
231,46,Yemen,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232,63,Zambia,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233,74,Zimbabwe,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [137]:
pop_22 = wp['2022 Population'].sum()
pop_70 = wp['1970 Population'].sum()

pop_22 - pop_70

np.int64(4279276381)

In [138]:
countries_by_continent = wp["Continent"].value_counts().reset_index()
countries_by_continent

       Continent  count
0         Africa     57
1           Asia     50
2         Europe     50
3  North America     40
4        Oceania     23
5  South America     14

In [139]:
wp.groupby(by="Continent").count()

,Rank,Country/Territory,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,...,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77
Continent,,,,,,,,,,,,,,,,,,,,,
Africa,57,57,57,57,57,57,57,57,57,57,...,0,0,0,0,0,0,0,0,0,0
Asia,50,50,50,50,50,50,50,50,50,50,...,0,0,0,0,0,0,0,0,0,0
Europe,50,50,50,50,50,50,50,50,50,50,...,0,0,0,0,0,0,0,0,0,0
North America,40,40,40,40,40,40,40,40,40,40,...,0,0,0,0,0,0,0,0,0,0
Oceania,23,23,23,23,23,23,23,23,23,23,...,0,0,0,0,0,0,0,0,0,0
South America,14,14,14,14,14,14,14,14,14,14,...,0,0,0,0,0,0,0,0,0,0

### Create the bar chart

In [140]:
fig= px.bar(countries_by_continent,
            x='Continent',
            y='count',
            color='Continent',
            text='count',
            title='Number of Countires by Contitnent',
           color_discrete_sequence = custom_palette )

In [ ]:
fig.update_layout(
xaxis_title='Continents',
yaxis_title='Number of Countries',
plot_bgcolor='rgba(0,0,0,0)',
font_family='Arial',
title_font_size=20 )

In [142]:
fig.show()

In [143]:
continent_population_percentage = wp.groupby('Continent')['World Population Percentage'].sum().reset_index()
continent_population_percentage

       Continent  World Population Percentage
0         Africa                        17.87
1           Asia                        59.19
2         Europe                         9.33
3  North America                         7.51
4        Oceania                         0.55
5  South America                         5.48

In [144]:
fig = go.Figure(data=[go.Pie(labels=continent_population_percentage['Continent'],
values=continent_population_percentage['World Population Percentage'])])

In [145]:
fig.update_layout(
title='World Population Percentage by Continent',
template='plotly',
paper_bgcolor='rgba(255,255,255,0)', 
plot_bgcolor='rgba(255,255,255,0)' 
)

In [146]:
fig.update_traces(marker=dict(colors=custom_palette, line=dict(color='#FFFFFF',
width=1)))
fig.show()

### Melt the DataFrame to have a long format

In [147]:

wp_melted = wp.melt(id_vars=['Continent'],
value_vars=['2022 Population', '2020 Population', '2015 Population','2010 Population', '2000 Population', '1990 Population','1980 Population',
            '1970 Population'],
var_name='Year',
value_name='Population')

In [148]:
wp_melted['Year'] = wp_melted['Year'].str.split().str[0].astype(int)
population_by_continent = wp_melted.groupby(['Continent',
'Year']).sum().reset_index()

In [149]:
fig = px.line(population_by_continent, x='Year', y='Population', color='Continent',
title='Population Trends by Continent Over Time',
labels={'Population': 'Population', 'Year': 'Year'},
color_discrete_sequence=custom_palette)
fig.update_layout(
template='plotly_white',
xaxis_title='Year',
yaxis_title='Population',
font_family='Arial',
title_font_size=20,
)
fig.update_traces(line=dict(width=3))
fig.show()

In [150]:
features=['1970 Population' ,'2020 Population']
for feature in features:
    fig = px.choropleth(wp,
                        locations='Country/Territory',
                        locationmode='country names',
                        color=feature,
                        hover_name='Country/Territory',
                        template='plotly_white',
                        title = feature)
fig.show()

C:\Users\AMITESH\AppData\Local\Temp\ipykernel_15048\195813007.py:3: DeprecationWarning: The library used by the *country names* `locationmode` option is changing in an upcoming version. Country names in existing plots may not work in the new version. To ensure consistent behavior, consider setting `locationmode` to *ISO-3*.
  fig = px.choropleth(wp,
C:\Users\AMITESH\AppData\Local\Temp\ipykernel_15048\195813007.py:3: DeprecationWarning: The library used by the *country names* `locationmode` option is changing in an upcoming version. Country names in existing plots may not work in the new version. To ensure consistent behavior, consider setting `locationmode` to *ISO-3*.
  fig = px.choropleth(wp,

In [151]:
growth = (wp.groupby(by='Country/Territory')['2022 Population'].sum()-wp.groupby(by='Country/Territory')
          ['1970 Population'].sum()).sort_values(ascending=False).head(8)

fig=px.bar(x=growth.index,
y=growth.values,
text=growth.values,
color=growth.values,
title='Growth Of Population From 1970 to 2020 (Top 8)',
template='plotly_white')
fig.update_layout(xaxis_title='Country',
yaxis_title='Population Growth')
fig.show()

In [152]:
top_8_populated_countries_1970 = wp.groupby('Country/Territory')['1970 Population'].sum().sort_values(ascending=False).head(8)
top_8_populated_countries_2022 = wp.groupby('Country/Territory')['2022 Population'].sum().sort_values(ascending=False).head(8)

features = {'top_8_populated_countries_1970': top_8_populated_countries_1970,
'top_8_populated_countries_2022': top_8_populated_countries_2022}
for feature_name, feature_data in features.items():
    year = feature_name.split('_')[-1] 
    fig = px.bar(x=feature_data.index,
                 y=feature_data.values,
                 text=feature_data.values,
                 color=feature_data.values,
                 title=f'Top 8 Most Populated Countries ({year})',
                 template='plotly_white')
    fig.update_layout(xaxis_title='Country',
                      yaxis_title='Population Growth')
fig.show()

In [153]:
sorted_df_growth = wp.sort_values(by='Growth Rate', ascending=False)
top_fastest = sorted_df_growth.head(6)
top_slowest = sorted_df_growth.tail(6)

In [154]:
def plot_population_trends(countries):
    n_cols = 2
    n_rows = (len(countries) + n_cols - 1) // n_cols

In [155]:

def plot_population_trends(countries):
    
    n_cols = 2
    n_rows = (len(countries) + n_cols - 1) // n_cols

    fig = sp.make_subplots(rows=n_rows, cols=n_cols, subplot_titles=countries,
                           horizontal_spacing=0.1, vertical_spacing=0.1)

    for i, country in enumerate(countries, start=1):
       
        country_wp = wp[wp['Country/Territory'] == country]

       
        country_melted = country_wp .melt(
            id_vars=['Country/Territory'],
            value_vars=['2022 Population', '2020 Population', '2015 Population',
                        '2010 Population', '2000 Population', '1990 Population',
                        '1980 Population', '1970 Population'],
            var_name='Year',
            value_name='Population'
        )

     
        country_melted['Year'] = country_melted['Year'].str.split().str[0].astype(int)

        
        line_fig = px.line(country_melted, x='Year', y='Population',
                           color='Country/Territory',
                           labels={'Population': 'Population', 'Year': 'Year'},
                           color_discrete_sequence=custom_palette)

       
        row = (i - 1) // n_cols + 1
        col = (i - 1) % n_cols + 1

        for trace in line_fig.data:
            fig.add_trace(trace, row=row, col=col)


    fig.update_layout(
        title='Population Trends of Selected Countries Over Time',
        template='plotly_white',
        font_family='Arial',
        title_font_size=20,
        showlegend=False,
        height=600 * n_rows,  
    )
    fig.update_traces(line=dict(width=3))
    fig.update_xaxes(title_text='Year')
    fig.update_yaxes(title_text='Population')
    fig.show()

In [156]:
fastest = top_fastest[['Country/Territory', 'Growth Rate']].sort_values(by='Growth Rate', ascending=False).reset_index(drop=True)
fastest
plot_population_trends(['Moldova', 'Poland', 'Niger', 'Syria', 'Slovakia', 'DR Congo'])

In [157]:
slowest = top_slowest[['Country/Territory', 'Growth Rate']].sort_values(by='Growth Rate', ascending=False).reset_index(drop=True)
slowest

  Country/Territory  Growth Rate
0            Latvia       0.9876
1         Lithuania       0.9869
2          Bulgaria       0.9849
3    American Samoa       0.9831
4           Lebanon       0.9816
5           Ukraine       0.9120

In [158]:
plot_population_trends(['Latvia', 'Lithuania', 'Bulgaria', 'American Samoa',
'Lebanon', 'Ukraine'])

In [159]:
land_by_country = wp.groupby('Country/Territory')[wp.columns[10]].sum().sort_values(ascending=False)
most_land = land_by_country.head(5)
least_land = land_by_country.tail(5)
print(most_land)
print(least_land)

Country/Territory
China            822534450
India            557501301
United States    200328340
Russia           130093010
Indonesia        115228394
Name: 1970 Population, dtype: int64
Country/Territory
Niue                5185
Saint Barthelemy    2417
Falkland Islands    2274
Tokelau             1714
Vatican City         752
Name: 1970 Population, dtype: int64

In [160]:
fig = sp.make_subplots(rows=1, cols=2, subplot_titles=("Countries with Most Land", "Countries with Least Land"))
fig.add_trace(go.Bar(x=most_land.index, y=most_land.values, name='Most Land', marker_color=custom_palette[0]), row=1, col=1)
fig.add_trace(go.Bar(x=least_land.index, y=least_land.values, name='Least Land', marker_color=custom_palette[1]), row=1, col=2)
fig.update_layout(title_text="Geographical Distribution of Land Area by Country", showlegend=False, template='plotly_white')
fig.update_yaxes(title_text="Area (km²)", row=1, col=1)
fig.update_yaxes(title_text="Area (km²)", row=1, col=2)
fig.show()

In [161]:
wp['Area per Person'] = wp[wp.columns[10]] / wp['2022 Population']
country_area_per_person = wp.groupby('Country/Territory')['Area per Person'].sum()
most_land_available = country_area_per_person.sort_values(ascending=False).head(5)
least_land_available = country_area_per_person.sort_values(ascending=False).tail(5)

In [162]:
fig = sp.make_subplots(rows=1, cols=2, subplot_titles=("Countries with Most Land Available Per Capita",
                                                       "Countries with Least Land Available Per Capita"))
fig.add_trace(go.Bar(x=most_land_available.index, y=most_land_available.values,
                     name='Most Land', marker_color=custom_palette[2]), row=1, col=1)
fig.add_trace(go.Bar(x=least_land_available.index, y=least_land_available.values,
name='Least Land', marker_color=custom_palette[3]), row=1, col=2)
fig.update_layout(title_text="Distribution of Available Land Area by Country Per Capita",
                  showlegend=False,
                  template='plotly_white')
fig.update_yaxes(title_text="Land Available Per Person", row=1, col=1)
fig.update_yaxes(title_text="Land Available Per Person", row=1, col=2)
fig.show()

In [163]:
wp.to_csv('world_population.csv', index=False)